from .normal_consistency import NormalConsistencyTrainer, NormalConsistencyTrainerWrapper
from .depth_distortion import DepthDistortionTrainer, DepthDistortionTrainerWrapper
from .combinations import NormalTrainerWrapper
